name: rep-mocap
on:
  pull_request:
    branches:
      - rep-mocap
  push:
    branches:
      - rep-mocap
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: rolling
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.15
        with:
          package-name: mocap4r2_control mocap4r2_control_msgs rqt_mocap4r2_control mocap4r2_marker_publisher mocap4r2_marker_viz mocap4r2_marker_viz_srvs
          target-ros2-distro: rolling
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependency_repos.repos
      - name: Codecov
        uses: codecov/codecov-action@v1.1.0
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false